name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'  # Adicionei cache para acelerar a instalação

      - name: Install dependencies
        run: npm ci  # Usando 'npm ci' ao invés de 'npm install' para instalação mais rápida e determinística
      - name: Build
        run: |
          echo "Construindo o projeto"
          npm install -g @angular/cli
          # Determinar o nome correto para o repositório
          export REPO_NAME="fit-log"  # Ajuste para o nome correto do seu repositório

          # Construir com o base-href correto
          ng build --configuration production --base-href="/$REPO_NAME/"

          # Verificar qual é o diretório de saída (docs ou dist/*)
          export OUTPUT_DIR=$(cat angular.json | grep -o '"outputPath": "[^"]*"' | cut -d'"' -f4)
          # Adiciona arquivo .nojekyll
          touch $OUTPUT_DIR/.nojekyll

          # Criar arquivo 404.html para redirecionamento
          cat > $OUTPUT_DIR/404.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecionando...</title>
            <script>sessionStorage.redirect = location.href;</script>
            <meta http-equiv="refresh" content="0;URL=/$REPO_NAME/">
          </head>
          <body>
            <h1>Redirecionando...</h1>
          </body>
          </html>
          EOF
          # Adicionar script de redirecionamento ao index.html de forma mais robusta
          # Usando node para modificar o HTML em vez de sed
          node -e "
            const fs = require('fs');
            const path = '$OUTPUT_DIR/index.html';
            let html = fs.readFileSync(path, 'utf8');
            const script = '<script>(function(){var redirect=sessionStorage.redirect;delete sessionStorage.redirect;if(redirect&&redirect!==location.href){history.replaceState(null,null,redirect.replace(location.origin,\"\"));}}());</script>';
            html = html.replace('<head>', '<head>'+script);
            fs.writeFileSync(path, html);
          "

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g angular-cli-ghpages

          # Determinar o diretório de output novamente
          export OUTPUT_DIR=$(cat angular.json | grep -o '"outputPath": "[^"]*"' | cut -d'"' -f4)
          export REPO_NAME="fit-log"  # Ajuste para o nome correto do seu repositório
          echo "Executando deploy para GitHub Pages do diretório $OUTPUT_DIR"
          npx angular-cli-ghpages --dir=$OUTPUT_DIR --repo=https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git --name="GitHub Actions" --email=renanrramossi@gmail.com --no-silent

      - name: Output deployment URL
        run: |
          echo "Seu site foi implantado em https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
